##
## EPITECH PROJECT, 2018
## Dante's star
## File description:
## tournament's Makefile
##

all:
	make -C ..
	cp ../generator/generator .
	cp ../solver/solver .

clean :
	echo

fclean : clean

re : fclean all
